# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class {{ .FormulaName }} < Formula
  desc "{{ .Description }}"
  homepage "https://gentabase.dev"
  version "{{ .Version }}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hk8xb/gentabase-cli/releases/download/v{{ .Version }}/gentabase_darwin_arm64.tar.gz"
      sha256 "{{ .Checksum.gentabase_darwin_arm64 }}"

      def install
        bin.install "gentabase"
        (bash_completion/"gentabase").write `#{bin}/gentabase completion bash`
        (fish_completion/"gentabase.fish").write `#{bin}/gentabase completion fish`
        (zsh_completion/"_gentabase").write `#{bin}/gentabase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hk8xb/gentabase-cli/releases/download/v{{ .Version }}/gentabase_darwin_amd64.tar.gz"
      sha256 "{{ .Checksum.gentabase_darwin_amd64 }}"

      def install
        bin.install "gentabase"
        (bash_completion/"gentabase").write `#{bin}/gentabase completion bash`
        (fish_completion/"gentabase.fish").write `#{bin}/gentabase completion fish`
        (zsh_completion/"_gentabase").write `#{bin}/gentabase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hk8xb/gentabase-cli/releases/download/v{{ .Version }}/gentabase_linux_arm64.tar.gz"
      sha256 "{{ .Checksum.gentabase_linux_arm64 }}"

      def install
        bin.install "gentabase"
        (bash_completion/"gentabase").write `#{bin}/gentabase completion bash`
        (fish_completion/"gentabase.fish").write `#{bin}/gentabase completion fish`
        (zsh_completion/"_gentabase").write `#{bin}/gentabase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hk8xb/gentabase-cli/releases/download/v{{ .Version }}/gentabase_linux_amd64.tar.gz"
      sha256 "{{ .Checksum.gentabase_linux_amd64 }}"

      def install
        bin.install "gentabase"
        (bash_completion/"gentabase").write `#{bin}/gentabase completion bash`
        (fish_completion/"gentabase.fish").write `#{bin}/gentabase completion fish`
        (zsh_completion/"_gentabase").write `#{bin}/gentabase completion zsh`
      end
    end
  end
end
